name: Laravel OpenAPI CI

on:
  push:
    branches:
      - 'feature/openapi'
    paths:
      - 'laravel-openapi/**'
      - '!**.md'
  pull_request:
    paths:
      - 'laravel-openapi/**'
      - '!**.md'
  schedule:
    - cron: "0 5 * * 4"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Install composer dependencies
      run: |
        cd laravel-openapi
        composer install --no-scripts
 
    - name: Prepare Laravel Application
      run: |
        cd laravel-openapi
        cp .env.ci .env
        php artisan key:generate
 
    - name: Run Testsuite
      run: |
        cd laravel-openapi
        vendor/bin/phpunit tests/
